-- MySQL Script generated by MySQL Workbench
-- Sun Nov  7 20:57:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema beautyhouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beautyhouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beautyhouse` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `beautyhouse` ;

-- -----------------------------------------------------
-- Table `beautyhouse`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautyhouse`.`brand` (
  `id` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beautyhouse`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautyhouse`.`customer` (
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beautyhouse`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautyhouse`.`manager` (
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beautyhouse`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautyhouse`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `cusAccount` VARCHAR(10) NOT NULL,
  `pid` VARCHAR(6) CHARACTER SET 'utf8' NOT NULL,
  `quantity` INT NOT NULL,
  `totalMoney` FLOAT NULL DEFAULT NULL,
  `dateOrder` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`orderId`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beautyhouse`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautyhouse`.`products` (
  `pid` VARCHAR(6) CHARACTER SET 'utf8' NOT NULL,
  `pname` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `typeid` VARCHAR(3) CHARACTER SET 'utf8' NOT NULL,
  `brand` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `image` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `price` FLOAT NOT NULL,
  `stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beautyhouse`.`producttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beautyhouse`.`producttype` (
  `tid` VARCHAR(3) CHARACTER SET 'utf8' NOT NULL,
  `tname` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
